// NACE Rev. 2 divisions (2-digit). Spain CNAE uses the same codes. Used for the sector dropdown and matching.
export const NACE_DIVISIONS: { code: string; name: string; section: string }[] = [
  { code: "01", name: "Crop and animal production, hunting", section: "A" },
  { code: "02", name: "Forestry and logging", section: "A" },
  { code: "03", name: "Fishing and aquaculture", section: "A" },
  { code: "05", name: "Mining of coal", section: "B" },
  { code: "06", name: "Extraction of crude petroleum and gas", section: "B" },
  { code: "08", name: "Other mining and quarrying", section: "B" },
  { code: "10", name: "Food products", section: "C" },
  { code: "11", name: "Beverages", section: "C" },
  { code: "13", name: "Textiles", section: "C" },
  { code: "14", name: "Wearing apparel", section: "C" },
  { code: "16", name: "Wood and wood products", section: "C" },
  { code: "17", name: "Paper and paper products", section: "C" },
  { code: "18", name: "Printing and reproduction", section: "C" },
  { code: "20", name: "Chemicals and chemical products", section: "C" },
  { code: "21", name: "Pharmaceutical products", section: "C" },
  { code: "22", name: "Rubber and plastic products", section: "C" },
  { code: "23", name: "Other non-metallic mineral products", section: "C" },
  { code: "24", name: "Basic metals", section: "C" },
  { code: "25", name: "Fabricated metal products", section: "C" },
  { code: "26", name: "Computer, electronic and optical products", section: "C" },
  { code: "27", name: "Electrical equipment", section: "C" },
  { code: "28", name: "Machinery and equipment", section: "C" },
  { code: "29", name: "Motor vehicles and trailers", section: "C" },
  { code: "30", name: "Other transport equipment", section: "C" },
  { code: "31", name: "Furniture", section: "C" },
  { code: "32", name: "Other manufacturing", section: "C" },
  { code: "33", name: "Repair and installation of machinery", section: "C" },
  { code: "35", name: "Electricity, gas, steam supply", section: "D" },
  { code: "36", name: "Water collection and supply", section: "E" },
  { code: "37", name: "Sewerage", section: "E" },
  { code: "38", name: "Waste collection, treatment, recycling", section: "E" },
  { code: "39", name: "Remediation and waste management services", section: "E" },
  { code: "41", name: "Construction of buildings", section: "F" },
  { code: "42", name: "Civil engineering", section: "F" },
  { code: "43", name: "Specialised construction activities", section: "F" },
  { code: "45", name: "Trade and repair of motor vehicles", section: "G" },
  { code: "46", name: "Wholesale trade", section: "G" },
  { code: "47", name: "Retail trade", section: "G" },
  { code: "49", name: "Land transport", section: "H" },
  { code: "50", name: "Water transport", section: "H" },
  { code: "51", name: "Air transport", section: "H" },
  { code: "52", name: "Warehousing and transport support", section: "H" },
  { code: "53", name: "Postal and courier activities", section: "H" },
  { code: "55", name: "Accommodation", section: "I" },
  { code: "56", name: "Food and beverage service", section: "I" },
  { code: "58", name: "Publishing activities", section: "J" },
  { code: "59", name: "Film, video, TV, music production", section: "J" },
  { code: "60", name: "Broadcasting", section: "J" },
  { code: "61", name: "Telecommunications", section: "J" },
  { code: "62", name: "Computer programming and consultancy", section: "J" },
  { code: "63", name: "Information services, data, web portals", section: "J" },
  { code: "64", name: "Financial services", section: "K" },
  { code: "65", name: "Insurance and pension", section: "K" },
  { code: "66", name: "Auxiliary financial activities", section: "K" },
  { code: "68", name: "Real estate", section: "L" },
  { code: "69", name: "Legal and accounting", section: "M" },
  { code: "70", name: "Head offices, management consultancy", section: "M" },
  { code: "71", name: "Architecture and engineering", section: "M" },
  { code: "72", name: "Scientific research and development", section: "M" },
  { code: "73", name: "Advertising and market research", section: "M" },
  { code: "74", name: "Other professional, scientific, technical", section: "M" },
  { code: "75", name: "Veterinary activities", section: "M" },
  { code: "77", name: "Rental and leasing", section: "N" },
  { code: "78", name: "Employment activities", section: "N" },
  { code: "79", name: "Travel agency and tour operators", section: "N" },
  { code: "80", name: "Security and investigation", section: "N" },
  { code: "81", name: "Services to buildings and landscape", section: "N" },
  { code: "82", name: "Office administrative and business support", section: "N" },
  { code: "84", name: "Public administration", section: "O" },
  { code: "85", name: "Education", section: "P" },
  { code: "86", name: "Human health", section: "Q" },
  { code: "87", name: "Residential care", section: "Q" },
  { code: "88", name: "Social work", section: "Q" },
  { code: "90", name: "Creative, arts and entertainment", section: "R" },
  { code: "91", name: "Libraries, archives, museums", section: "R" },
  { code: "93", name: "Sports, amusement and recreation", section: "R" },
  { code: "94", name: "Membership organisations", section: "S" },
  { code: "95", name: "Repair of computers and household goods", section: "S" },
  { code: "96", name: "Other personal services", section: "S" },
];

export const NACE_BY_CODE = new Map(NACE_DIVISIONS.map((d) => [d.code, d]));
